### ISSUE TITLE
Full-text index search no working very well with Chinese

### ISSUE THREAD

**Issue by jiayouchongmingniao** [ONLYOFFICE/Docker-CommunityServer#178] opened 2022-12-20 15:28 UTC
Dear support,

I am running community server 12.1.0.1760, ES 7.16.3. Searching Chinese doc often get some of occurrences of key word(also in Chinese), not all of them. As ES could be configured with more plugin(text analyzer) to deal with the languages of various kinds, Could it possible to make ES better working from onlyoffice side with configuration?

Currently, shipped ES only get plugin ingest-attachment installed, which seems not working well enough with Chinese.

I use the global search in the right-up Conner. I want to do a search on the content of documents as well, not only on the file name. It looks not work so well, however.

Full-Text Search has been enabled correctly. The problem is searching results are not complete, missing a lot. I wonder if there could be some way to configure the ES to use more sophistecated text analyzer.

THanks for your great support in advance !

**Comment by Carazyda** [comment] 2022-12-20 15:44
Hello @jiayouchongmingniao this looks like a duplicate of https://github.com/ONLYOFFICE/Docker-CommunityServer/issues/169. Or please provide more information with an example of your issue.

**Comment by jiayouchongmingniao** [comment] 2022-12-22 02:12
OK

**Comment by jiayouchongmingniao** [comment] 2022-12-23 15:52
![1671810761442](https://user-images.githubusercontent.com/55178588/209363296-913b1c24-5049-4f80-a6e8-11e606f231bc.png)

**Comment by jiayouchongmingniao** [comment] 2022-12-23 15:53
![1671810817233](https://user-images.githubusercontent.com/55178588/209363407-2d609a6c-d1a8-4b71-b6cb-e07a09457459.png)

**Comment by jiayouchongmingniao** [comment] 2022-12-23 15:54
![1671810860068](https://user-images.githubusercontent.com/55178588/209363492-2ca29360-0ab4-40fb-9f32-eff935e12f94.png)

**Comment by jiayouchongmingniao** [comment] 2022-12-23 15:55
keyword "天翼云" , but search result is not completed

**Comment by jiayouchongmingniao** [comment] 2022-12-23 15:55
![1671810948670](https://user-images.githubusercontent.com/55178588/209363644-de24b81e-198f-476a-bb1d-77e6649fefca.png)

**Comment by jiayouchongmingniao** [comment] 2022-12-23 15:56
has reindexed all,  but same result with search keyword "天翼云"
change to other keyword, similar situation with Chinese ...

**Comment by jiayouchongmingniao** [comment] 2022-12-23 16:02
![1671811231822](https://user-images.githubusercontent.com/55178588/209364261-a4572586-3383-40d6-b2fd-7cc3462c5958.png)

![1671811262593](https://user-images.githubusercontent.com/55178588/209364393-e0c7492f-8b27-435f-9e25-437ede89548d.jpg)

![1671811363709](https://user-images.githubusercontent.com/55178588/209364526-f260bb35-62f6-4b38-8799-4ddaaad35d1c.png)

**Comment by gaord** [comment] 2022-12-23 16:06
I think one can install additional analyzer for ES plugin for a better search experience of languages. Is it feasible anyway from your point of view?
@Carazyda

**Comment by Carazyda** [comment] 2022-12-23 16:45
Yes, this is a duplicate of https://github.com/ONLYOFFICE/Docker-CommunityServer/issues/169. Search in Chinese only works with a complete match. Unfortunately, I can't help you with setting up the plugins for the ES.

**Closed by Carazyda** 2022-12-23 16:45 UTC
