### ISSUE TITLE
Issue with control panel exited: www (exit status 1; not expected)

### ISSUE THREAD

**Issue by ovizii** [ONLYOFFICE/Docker-CommunityServer#181] opened 2023-02-01 14:31 UTC
Trying to get this all working via docker-compose.yml I see these errors in the control panel container. Any ideas what to check for?

```
docker logs -f onlyoffice-control-panel                                                                         
/usr/lib/python2.7/dist-packages/supervisor/options.py:297: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.                                                                                                                 
  'Supervisord is running as root and it is searching '                                                                                              
2023-02-01 14:27:00,076 CRIT Supervisor running as root (no user in config file)                                                                     
2023-02-01 14:27:00,076 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing                                            
2023-02-01 14:27:00,085 INFO RPC interface 'supervisor' initialized                                                                                  
2023-02-01 14:27:00,085 CRIT Server 'unix_http_server' running without any HTTP authentication checking                                              
2023-02-01 14:27:00,085 INFO supervisord started with pid 1                                                                                          
2023-02-01 14:27:01,087 INFO spawned: 'www' with pid 15                                                                                              
2023-02-01 14:27:01,240 INFO exited: www (exit status 1; not expected)                                                                               
2023-02-01 14:27:02,241 INFO spawned: 'www' with pid 22                                                                                              
2023-02-01 14:27:02,336 INFO exited: www (exit status 1; not expected)                                                                               
2023-02-01 14:27:04,338 INFO spawned: 'www' with pid 29                                                                                              
2023-02-01 14:27:04,451 INFO exited: www (exit status 1; not expected)                                                                               
2023-02-01 14:27:07,455 INFO spawned: 'www' with pid 36                                                                                              
2023-02-01 14:27:07,597 INFO exited: www (exit status 1; not expected)                                                                               
2023-02-01 14:27:08,598 INFO gave up: www entered FATAL state, too many start retries too quickly 
```

**Comment by Carazyda** [comment] 2023-02-01 15:42
Duplicate of https://github.com/ONLYOFFICE/Docker-CommunityServer/issues/174.

**Closed by Carazyda** 2023-02-01 15:42 UTC
