### ISSUE TITLE
Workspace does not support full-text search in Chinese

### ISSUE THREAD

**Issue by aisuhua** [ONLYOFFICE/Docker-CommunityServer#169] opened 2022-09-09 01:38 UTC
Docker-CommunityServer Version: v12.0.1

```sh
git clone https://github.com/ONLYOFFICE/Docker-CommunityServer.git
cd Docker-CommunityServer
docker-compose -f docker-compose.workspace.yml up 
```

![](https://forum.onlyoffice.com/uploads/default/original/2X/6/664a970a4246b8e0e889f8f3eb17073092488411.gif)

**Comment by Misokados** [comment] 2022-09-09 07:42
Hello @aisuhua 
Please do not post the same question to different communication channels. As far as I see, you posted this issue on https://forum.onlyoffice.com/ and we confirmed that this is a known bug. We are working on it already.
If you have other questions which are related to this situation, please continue discission on the forum.

**Comment by Carazyda** [comment] 2022-09-09 09:29
Duplicate of https://github.com/ONLYOFFICE/CommunityServer/issues/271

**Closed by Carazyda** 2022-09-09 09:29 UTC
